export type EventVisualPriority = "ambient" | "featured" | "drama";

export const EVENT_VISUAL_ICON_KEYS = [
  "birth",
  "bond",
  "breach",
  "crown",
  "decay",
  "footstep",
  "gift",
  "harvest",
  "hearth",
  "home",
  "ruin",
  "skull",
  "spark",
  "speech",
  "theft",
  "thought",
  "wound",
  "world",
] as const;

export type EventVisualIconKey = (typeof EVENT_VISUAL_ICON_KEYS)[number];

export interface EventVisualMetadata {
  glyph: string;
  iconKey: EventVisualIconKey;
  iconLabel: string;
  medallionLabel: string;
  priority: EventVisualPriority;
  accent: string;
  salient: boolean;
}

export const EVENT_VISUAL_EVENT_TYPES = [
  "agent_born",
  "agent_died",
  "agent_decayed",
  "agent_paralyzed",
  "agent_recovered",
  "agent_left_region",
  "agent_entered_region",
  "speak",
  "self_talk",
  "resource_changed",
  "resource_transferred",
  "agent_started_hoarding",
  "mating_initiated",
  "mating_rejected",
  "mating_proposal_invalidated",
  "mating_proposal_timeout",
  "attack",
  "home_built",
  "hearth_used",
  "home_joined",
  "home_left",
  "home_started_hoarding",
  "home_collapsed",
  "home_breached",
  "home_thieved",
  "home_colonized",
  "ruins_scavenged",
  "simulation_started",
] as const;

export type EventVisualEventType = (typeof EVENT_VISUAL_EVENT_TYPES)[number];

export const EVENT_VISUAL_CATALOG = {
  agent_born: {
    glyph: "BN",
    iconKey: "birth",
    iconLabel: "Birth",
    medallionLabel: "Birth",
    priority: "featured",
    accent: "#f0c66f",
    salient: true,
  },
  agent_died: {
    glyph: "DD",
    iconKey: "skull",
    iconLabel: "Death",
    medallionLabel: "Death",
    priority: "drama",
    accent: "#c74f45",
    salient: true,
  },
  agent_decayed: {
    glyph: "DC",
    iconKey: "decay",
    iconLabel: "Body decay",
    medallionLabel: "Decay",
    priority: "featured",
    accent: "#9b8054",
    salient: true,
  },
  agent_paralyzed: {
    glyph: "PZ",
    iconKey: "wound",
    iconLabel: "Paralysis",
    medallionLabel: "Paralysis",
    priority: "drama",
    accent: "#c74f45",
    salient: true,
  },
  agent_recovered: {
    glyph: "RV",
    iconKey: "spark",
    iconLabel: "Recovery",
    medallionLabel: "Recovery",
    priority: "featured",
    accent: "#f0c66f",
    salient: true,
  },
  agent_left_region: {
    glyph: "LT",
    iconKey: "footstep",
    iconLabel: "Departure",
    medallionLabel: "Depart",
    priority: "ambient",
    accent: "#6fc7bd",
    salient: false,
  },
  agent_entered_region: {
    glyph: "EN",
    iconKey: "footstep",
    iconLabel: "Arrival",
    medallionLabel: "Arrive",
    priority: "ambient",
    accent: "#6fc7bd",
    salient: false,
  },
  speak: {
    glyph: "SP",
    iconKey: "speech",
    iconLabel: "Speech",
    medallionLabel: "Speech",
    priority: "featured",
    accent: "#6fc7bd",
    salient: false,
  },
  self_talk: {
    glyph: "TH",
    iconKey: "thought",
    iconLabel: "Private thought",
    medallionLabel: "Thought",
    priority: "featured",
    accent: "#d6b96f",
    salient: false,
  },
  resource_changed: {
    glyph: "RS",
    iconKey: "harvest",
    iconLabel: "Harvest",
    medallionLabel: "Harvest",
    priority: "ambient",
    accent: "#8fac6d",
    salient: false,
  },
  resource_transferred: {
    glyph: "TX",
    iconKey: "gift",
    iconLabel: "Resource gift",
    medallionLabel: "Gift",
    priority: "ambient",
    accent: "#8fac6d",
    salient: false,
  },
  agent_started_hoarding: {
    glyph: "HG",
    iconKey: "crown",
    iconLabel: "Being hoard",
    medallionLabel: "Hoard",
    priority: "ambient",
    accent: "#d6b96f",
    salient: false,
  },
  mating_initiated: {
    glyph: "MI",
    iconKey: "bond",
    iconLabel: "Bond proposed",
    medallionLabel: "Bond",
    priority: "featured",
    accent: "#d9a8bd",
    salient: true,
  },
  mating_rejected: {
    glyph: "MR",
    iconKey: "bond",
    iconLabel: "Bond refused",
    medallionLabel: "Refused",
    priority: "featured",
    accent: "#d9a8bd",
    salient: true,
  },
  mating_proposal_invalidated: {
    glyph: "MX",
    iconKey: "bond",
    iconLabel: "Bond invalidated",
    medallionLabel: "Invalid",
    priority: "featured",
    accent: "#d9a8bd",
    salient: true,
  },
  mating_proposal_timeout: {
    glyph: "MT",
    iconKey: "bond",
    iconLabel: "Bond timed out",
    medallionLabel: "Timeout",
    priority: "featured",
    accent: "#d9a8bd",
    salient: true,
  },
  attack: {
    glyph: "AT",
    iconKey: "wound",
    iconLabel: "Attack",
    medallionLabel: "Attack",
    priority: "drama",
    accent: "#c74f45",
    salient: false,
  },
  home_built: {
    glyph: "HB",
    iconKey: "home",
    iconLabel: "Home built",
    medallionLabel: "Home",
    priority: "featured",
    accent: "#d6b96f",
    salient: true,
  },
  hearth_used: {
    glyph: "HR",
    iconKey: "hearth",
    iconLabel: "Hearth used",
    medallionLabel: "Hearth",
    priority: "featured",
    accent: "#d6b96f",
    salient: true,
  },
  home_joined: {
    glyph: "HJ",
    iconKey: "bond",
    iconLabel: "Home joined",
    medallionLabel: "Join",
    priority: "ambient",
    accent: "#d6b96f",
    salient: false,
  },
  home_left: {
    glyph: "HL",
    iconKey: "footstep",
    iconLabel: "Home left",
    medallionLabel: "Leave",
    priority: "ambient",
    accent: "#d6b96f",
    salient: false,
  },
  home_started_hoarding: {
    glyph: "HV",
    iconKey: "crown",
    iconLabel: "Vault hoard",
    medallionLabel: "Vault",
    priority: "ambient",
    accent: "#d6b96f",
    salient: false,
  },
  home_collapsed: {
    glyph: "HC",
    iconKey: "ruin",
    iconLabel: "Home ruin",
    medallionLabel: "Ruin",
    priority: "drama",
    accent: "#9b8054",
    salient: true,
  },
  home_breached: {
    glyph: "BR",
    iconKey: "breach",
    iconLabel: "Home breach",
    medallionLabel: "Breach",
    priority: "drama",
    accent: "#d96e3f",
    salient: true,
  },
  home_thieved: {
    glyph: "VT",
    iconKey: "theft",
    iconLabel: "Vault theft",
    medallionLabel: "Theft",
    priority: "drama",
    accent: "#d96e3f",
    salient: true,
  },
  home_colonized: {
    glyph: "CZ",
    iconKey: "crown",
    iconLabel: "Home claimed",
    medallionLabel: "Claim",
    priority: "drama",
    accent: "#d96e3f",
    salient: true,
  },
  ruins_scavenged: {
    glyph: "RU",
    iconKey: "ruin",
    iconLabel: "Ruin scavenged",
    medallionLabel: "Scavenge",
    priority: "featured",
    accent: "#9b8054",
    salient: true,
  },
  simulation_started: {
    glyph: "ON",
    iconKey: "world",
    iconLabel: "World start",
    medallionLabel: "World",
    priority: "featured",
    accent: "#ede4d2",
    salient: false,
  },
} as const satisfies Record<EventVisualEventType, EventVisualMetadata>;

export function isEventVisualEventType(type: string): type is EventVisualEventType {
  return Object.hasOwn(EVENT_VISUAL_CATALOG, type);
}

export function getEventVisualMetadata(
  type: string,
): EventVisualMetadata | undefined {
  return isEventVisualEventType(type) ? EVENT_VISUAL_CATALOG[type] : undefined;
}
